### ISSUE TITLE
Contributor User Bugs

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/admithub-telescope-theme#38]
Contributor avatars no longer show up next to their answers.  See this page:
https://college.admithub.com/posts/gj5ExKrr8da9yuntS/p/paying-for-college-

We are no longer displaying comment counts on the contributors page:
https://college.admithub.com/partners-and-contributors

**Comment by pcorey** [comment]
The fix for both of these are pushed to master.

I did not deploy the changes.

**Comment by AndrewMagliozzi** [comment]
Thanks Pete!  I am at a conference without my laptop for the evening. Won't have time to deploy till tonight or tomorrow.

**Comment by AndrewMagliozzi** [comment]
deployed!
